import type { BeautyConfig, FoodConfig, ProfessionalConfig } from '@/lib/vitrine-types'

export const beautyDemo: BeautyConfig = {
  category: 'beauty',
  businessName: 'Atelier Beleza',
  tagline: 'Onde a beleza encontra a arte. Tratamentos personalizados que realçam a sua essência natural.',
  heroImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1920&q=80',
  accentColor: '#D4A574',
  ambiance: 'Spa & Estética',
  bookingUrl: '#agendar',
  contact: {
    phone: '+351 912 345 678',
    whatsapp: '+351912345678',
    email: 'info@atelierbeleza.pt',
    address: 'Av. da Liberdade, 245, Lisboa',
    googleMapsUrl: 'https://maps.google.com/?q=Av.+da+Liberdade+245+Lisboa',
  },
  social: {
    instagram: 'https://instagram.com/atelierbeleza',
    facebook: 'https://facebook.com/atelierbeleza',
  },
  hours: [
    { day: 'Segunda-feira', hours: '10:00 - 19:00' },
    { day: 'Terça-feira', hours: '10:00 - 19:00' },
    { day: 'Quarta-feira', hours: '10:00 - 19:00' },
    { day: 'Quinta-feira', hours: '10:00 - 20:00' },
    { day: 'Sexta-feira', hours: '10:00 - 20:00' },
    { day: 'Sábado', hours: '09:00 - 18:00' },
    { day: 'Domingo', closed: true, hours: '' },
  ],
  services: [
    {
      id: '1',
      name: 'Corte & Styling',
      description: 'Corte personalizado com lavagem e styling',
      price: 'Desde 35€',
      duration: '45 min',
      category: 'Cabelo',
      image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80',
    },
    {
      id: '2',
      name: 'Coloração',
      description: 'Coloração profissional com produtos premium',
      price: 'Desde 60€',
      duration: '90 min',
      category: 'Cabelo',
      image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&q=80',
    },
    {
      id: '3',
      name: 'Madeixas & Balayage',
      description: 'Técnicas de iluminação natural',
      price: 'Desde 85€',
      duration: '120 min',
      category: 'Cabelo',
    },
    {
      id: '4',
      name: 'Tratamento Facial Premium',
      description: 'Limpeza profunda + hidratação intensiva',
      price: '75€',
      duration: '60 min',
      category: 'Rosto',
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&q=80',
    },
    {
      id: '5',
      name: 'Microagulhamento',
      description: 'Estimulação do colagénio para rejuvenescimento',
      price: '95€',
      duration: '45 min',
      category: 'Rosto',
    },
    {
      id: '6',
      name: 'Manicure & Pedicure',
      description: 'Cuidado completo das mãos e pés',
      price: '45€',
      duration: '75 min',
      category: 'Mãos & Pés',
      image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&q=80',
    },
    {
      id: '7',
      name: 'Verniz Gel',
      description: 'Aplicação de verniz gel com duração até 3 semanas',
      price: '30€',
      duration: '45 min',
      category: 'Mãos & Pés',
    },
    {
      id: '8',
      name: 'Massagem Relaxante',
      description: 'Massagem corporal para alívio do stress',
      price: '65€',
      duration: '60 min',
      category: 'Corpo',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
    },
  ],
  team: [
    {
      id: '1',
      name: 'Sofia Almeida',
      role: 'Diretora & Colorista',
      image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&q=80',
      specialties: ['Coloração', 'Balayage', 'Corte Feminino'],
    },
    {
      id: '2',
      name: 'Mariana Costa',
      role: 'Esteticista',
      image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&q=80',
      specialties: ['Tratamentos Faciais', 'Microagulhamento'],
    },
    {
      id: '3',
      name: 'Beatriz Santos',
      role: 'Nail Artist',
      image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80',
      specialties: ['Nail Art', 'Verniz Gel', 'Extensões'],
    },
  ],
  gallery: [
    { id: '1', src: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80', alt: 'Salão' },
    { id: '2', src: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80', alt: 'Styling' },
    { id: '3', src: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80', alt: 'Facial' },
    { id: '4', src: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80', alt: 'Nails' },
    { id: '5', src: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', alt: 'Ambiente' },
    { id: '6', src: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80', alt: 'Massagem' },
  ],
  testimonials: [
    {
      id: '1',
      name: 'Ana Ferreira',
      text: 'O melhor salão de Lisboa! A Sofia fez um trabalho incrível no meu cabelo. Ambiente sofisticado e equipa muito profissional.',
      rating: 5,
      date: 'Há 2 semanas',
    },
    {
      id: '2',
      name: 'Carla Mendes',
      text: 'Fiz um tratamento facial e saí completamente renovada. Produtos de qualidade e atendimento impecável.',
      rating: 5,
      date: 'Há 1 mês',
    },
    {
      id: '3',
      name: 'Rita Sousa',
      text: 'A Beatriz é uma artista! As minhas unhas nunca ficaram tão bonitas. Recomendo a todas as minhas amigas.',
      rating: 5,
      date: 'Há 3 semanas',
    },
  ],
}

export const foodDemo: FoodConfig = {
  category: 'food',
  businessName: 'Tasca do Porto',
  tagline: 'Sabores autênticos do Norte. Cozinha tradicional portuguesa com um toque contemporâneo no coração do Porto.',
  heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&q=80',
  accentColor: '#8B4513',
  cuisineType: 'Cozinha Portuguesa',
  reservationUrl: '#reservar',
  deliveryUrl: '#delivery',
  contact: {
    phone: '+351 223 456 789',
    whatsapp: '+351223456789',
    email: 'reservas@tascadoporto.pt',
    address: 'Rua das Flores, 123, Porto',
    googleMapsUrl: 'https://maps.google.com/?q=Rua+das+Flores+123+Porto',
  },
  social: {
    instagram: 'https://instagram.com/tascadoporto',
    facebook: 'https://facebook.com/tascadoporto',
  },
  hours: [
    { day: 'Segunda-feira', closed: true, hours: '' },
    { day: 'Terça-feira', hours: '12:00 - 15:00 | 19:00 - 23:00' },
    { day: 'Quarta-feira', hours: '12:00 - 15:00 | 19:00 - 23:00' },
    { day: 'Quinta-feira', hours: '12:00 - 15:00 | 19:00 - 23:00' },
    { day: 'Sexta-feira', hours: '12:00 - 15:00 | 19:00 - 00:00' },
    { day: 'Sábado', hours: '12:00 - 00:00' },
    { day: 'Domingo', hours: '12:00 - 16:00' },
  ],
  services: [],
  menu: [
    {
      id: 'entradas',
      name: 'Entradas',
      description: 'Para abrir o apetite',
      items: [
        {
          id: '1',
          name: 'Tábua de Queijos e Enchidos',
          description: 'Seleção de queijos da Serra e enchidos transmontanos',
          price: '16€',
          category: 'entradas',
          image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=400&q=80',
          featured: true,
        },
        {
          id: '2',
          name: 'Pataniscas de Bacalhau',
          description: 'Receita tradicional com maionese de coentros',
          price: '9€',
          category: 'entradas',
          image: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=400&q=80',
        },
        {
          id: '3',
          name: 'Alheira Frita',
          description: 'Com grelos salteados e ovo estrelado',
          price: '11€',
          category: 'entradas',
          image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80',
          tags: ['Popular'],
        },
      ],
    },
    {
      id: 'pratos',
      name: 'Pratos Principais',
      description: 'Os clássicos da casa',
      items: [
        {
          id: '4',
          name: 'Francesinha',
          description: 'O ícone do Porto. Pão, carnes variadas, queijo e molho secreto',
          price: '14€',
          category: 'pratos',
          image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
          featured: true,
          tags: ['Especialidade'],
        },
        {
          id: '5',
          name: 'Bacalhau à Lagareiro',
          description: 'Com batata a murro e azeite DOP',
          price: '22€',
          category: 'pratos',
          image: 'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=400&q=80',
        },
        {
          id: '6',
          name: 'Polvo à Lagareiro',
          description: 'Polvo grelhado com batatas ao murro',
          price: '24€',
          category: 'pratos',
          image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
          tags: ['Premium'],
        },
        {
          id: '7',
          name: 'Arroz de Pato',
          description: 'Receita da avó com pato desfiado e chouriço',
          price: '18€',
          category: 'pratos',
          image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80',
        },
        {
          id: '8',
          name: 'Bitoque',
          description: 'Bife com ovo a cavalo, arroz e batata frita',
          price: '13€',
          category: 'pratos',
          image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80',
        },
      ],
    },
    {
      id: 'sobremesas',
      name: 'Sobremesas',
      description: 'O doce final perfeito',
      items: [
        {
          id: '9',
          name: 'Pudim Abade de Priscos',
          description: 'Receita conventual com toucinho',
          price: '6€',
          category: 'sobremesas',
          image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&q=80',
        },
        {
          id: '10',
          name: 'Leite Creme Queimado',
          description: 'Cremoso e caramelizado na hora',
          price: '5€',
          category: 'sobremesas',
          image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
        },
        {
          id: '11',
          name: 'Toucinho do Céu',
          description: 'Doce de amêndoa tradicional',
          price: '5.50€',
          category: 'sobremesas',
          image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80',
        },
      ],
    },
    {
      id: 'bebidas',
      name: 'Bebidas',
      items: [
        {
          id: '12',
          name: 'Vinho da Casa',
          description: 'Tinto ou Branco - Garrafa 750ml',
          price: '12€',
          category: 'bebidas',
          image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80',
        },
        {
          id: '13',
          name: 'Vinho do Porto',
          description: 'Copo de Ruby ou Tawny',
          price: '4€',
          category: 'bebidas',
          image: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=400&q=80',
        },
        {
          id: '14',
          name: 'Sangria',
          description: 'Jarro 1L - Receita da casa',
          price: '15€',
          category: 'bebidas',
          image: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?w=400&q=80',
          tags: ['Refrescante'],
        },
      ],
    },
  ],
  gallery: [
    { id: '1', src: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80', alt: 'Interior' },
    { id: '2', src: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80', alt: 'Francesinha' },
    { id: '3', src: 'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=800&q=80', alt: 'Bacalhau' },
    { id: '4', src: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800&q=80', alt: 'Entradas' },
    { id: '5', src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80', alt: 'Ambiente' },
    { id: '6', src: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80', alt: 'Sobremesa' },
  ],
  testimonials: [
    {
      id: '1',
      name: 'João Silva',
      text: 'A melhor francesinha que já comi! O molho é divino e o ambiente é muito acolhedor. Voltarei sempre que estiver no Porto.',
      rating: 5,
      date: 'Há 1 semana',
    },
    {
      id: '2',
      name: 'Maria Santos',
      text: 'Comida tradicional portuguesa de excelência. O bacalhau à lagareiro estava perfeito. Pessoal muito simpático.',
      rating: 5,
      date: 'Há 2 semanas',
    },
    {
      id: '3',
      name: 'Pedro Costa',
      text: 'Levei turistas estrangeiros e ficaram encantados. Preços justos para a qualidade. O arroz de pato é imperdível!',
      rating: 5,
      date: 'Há 1 mês',
    },
  ],
}

export const professionalDemo: ProfessionalConfig = {
  category: 'professional',
  businessName: 'Dra. Marta Oliveira',
  tagline: 'Psicóloga Clínica especializada em ansiedade, depressão e desenvolvimento pessoal. Um espaço seguro para o seu crescimento emocional.',
  heroImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1920&q=80',
  accentColor: '#7C3AED',
  consultationUrl: '#consulta',
  areas: ['Ansiedade', 'Depressão', 'Autoestima', 'Relações', 'Gestão de Stress'],
  contact: {
    phone: '+351 912 345 678',
    whatsapp: '+351912345678',
    email: 'consultas@dramartaoliveira.pt',
    address: 'Av. da Liberdade, 200, 3º andar, Lisboa',
    googleMapsUrl: 'https://maps.google.com/?q=Av.+da+Liberdade+200+Lisboa',
  },
  social: {
    instagram: 'https://instagram.com/dra.martaoliveira',
    linkedin: 'https://linkedin.com/in/martaoliveira',
  },
  hours: [
    { day: 'Segunda-feira', hours: '09:00 - 19:00' },
    { day: 'Terça-feira', hours: '09:00 - 19:00' },
    { day: 'Quarta-feira', hours: '09:00 - 19:00' },
    { day: 'Quinta-feira', hours: '09:00 - 19:00' },
    { day: 'Sexta-feira', hours: '09:00 - 17:00' },
    { day: 'Sábado', hours: '10:00 - 13:00' },
    { day: 'Domingo', closed: true, hours: '' },
  ],
  services: [
    {
      id: '1',
      name: 'Consulta de Psicologia',
      description: 'Sessão individual de 50 minutos. Abordagem integrativa adaptada às suas necessidades específicas.',
      price: '60€',
    },
    {
      id: '2',
      name: 'Primeira Consulta',
      description: 'Avaliação inicial para compreensão do motivo de consulta e definição de objetivos terapêuticos.',
      price: '50€',
    },
    {
      id: '3',
      name: 'Consulta Online',
      description: 'Sessão por videochamada, ideal para quem tem dificuldade de deslocação ou vive no estrangeiro.',
      price: '55€',
    },
    {
      id: '4',
      name: 'Pack 4 Sessões',
      description: 'Compromisso com o processo terapêutico. Inclui material de apoio entre sessões.',
      price: '200€',
    },
    {
      id: '5',
      name: 'Terapia de Casal',
      description: 'Sessões de 75 minutos para trabalhar a comunicação e fortalecer a relação.',
      price: '80€',
    },
    {
      id: '6',
      name: 'Avaliação Psicológica',
      description: 'Avaliação completa com relatório detalhado para fins clínicos ou profissionais.',
      price: '150€',
    },
  ],
  team: [
    {
      id: '1',
      name: 'Dra. Marta Oliveira',
      title: 'Psicóloga Clínica',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
      credentials: [
        { title: 'Mestrado Integrado em Psicologia Clínica', institution: 'Universidade de Lisboa', year: '2012' },
        { title: 'Especialização em Terapia Cognitivo-Comportamental', institution: 'APTC', year: '2015' },
        { title: 'Formação em EMDR - Nível II', institution: 'EMDR Europe', year: '2018' },
        { title: 'Membro Efetivo da Ordem dos Psicólogos Portugueses', institution: 'Cédula nº 12345', year: '' },
      ],
      specialties: ['Ansiedade', 'Depressão', 'Trauma', 'Autoestima', 'Relações Interpessoais'],
    },
  ],
  testimonials: [
    {
      id: '1',
      name: 'Ana R.',
      text: 'A Dra. Marta ajudou-me a superar uma fase muito difícil da minha vida. Sinto-me uma pessoa completamente diferente, mais confiante e em paz comigo mesma.',
      rating: 5,
      date: 'Há 2 semanas',
    },
    {
      id: '2',
      name: 'Miguel S.',
      text: 'Depois de anos a sofrer com ansiedade, finalmente encontrei alguém que me compreende e me deu ferramentas práticas para o dia-a-dia. Recomendo vivamente.',
      rating: 5,
      date: 'Há 1 mês',
    },
    {
      id: '3',
      name: 'Catarina M.',
      text: 'O ambiente do consultório é muito acolhedor e a Dra. Marta faz-nos sentir completamente à vontade. As sessões online funcionam muito bem.',
      rating: 5,
      date: 'Há 3 semanas',
    },
  ],
}